spring.datasource.url=jdbc:postgresql://localhost:5432/cofy_db
spring.datasource.username=postgres
spring.datasource.password=KarmannikGay

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
